sudo: required

services:
  - docker

env:
  global:
  - REPO=netresearch/akeneo-app

script:
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
 # Tag types:
 #   0: Branch without version relation
 #   1: Version branch (1.6/1.7)
 #   2: Version tag (1.7.6/1.6.18)
 - export TAG_TYPE=$(grep -o "\." <<< "$TRAVIS_BRANCH" | wc -l)
 - >
     eval $(cat .env);
     BOOTSTRAP_VERSION="dev-$TRAVIS_BRANCH";
     if [ "$TAG_TYPE" == "1" ]; then
       BOOTSTRAP_VERSION="$TRAVIS_BRANCH.x-dev";
     fi;
     if [ "$TAG_TYPE" == "2" ]; then
       BOOTSTRAP_VERSION="$TAG";
     fi;
     COUNTER=0;
     while : ; do
       PACKAGIST_OUTPUT=$(composer show -al netresearch/akeneo-bootstrap $BOOTSTRAP_VERSION 2>&1 || "")
       PACKAGIST_UPDATED=$(echo $PACKAGIST_OUTPUT | grep $TRAVIS_COMMIT);
       if [ "$PACKAGIST_UPDATED" ];
       then
         break;
       else
         echo -n "Latest commit on packagist version doesn't match current - ";
         if [ $COUNTER -lt 20 ];
         then
           let COUNTER+=1;
           echo "retrying";
           sleep 2;
         else
           echo "FAILED (see below)";
           echo "Command: composer show -al netresearch/akeneo-bootstrap $BOOTSTRAP_VERSION";
           echo "Expected commit: $TRAVIS_COMMIT";
           echo "Output: $PACKAGIST_OUTPUT";
           exit 1;
         fi;
       fi;
     done;
     echo "Building with:";
     echo "  AKENEO_VERSION: $AKENEO_VERSION";
     echo "  AKENEO_DIRECTORY: $AKENEO_DIRECTORY";
     echo "  PACKAGES_DIRECTORY: $PACKAGES_DIRECTORY";
     echo "  BOOTSTRAP_VERSION: $BOOTSTRAP_VERSION";
     docker build \
       --build-arg "AKENEO_VERSION=$AKENEO_VERSION" \
       --build-arg "AKENEO_DIRECTORY=$AKENEO_DIRECTORY" \
       --build-arg "PACKAGES_DIRECTORY=$PACKAGES_DIRECTORY" \
       --build-arg "BOOTSTRAP_VERSION=$BOOTSTRAP_VERSION" \
       -t "$REPO:$TAG" .

after_success:
 - >
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      if [ "$TAG" == "latest" ]; then
        ALIAS=$(echo "$AKENEO_VERSION" | cut -c -3);
        docker tag "$REPO:$TAG" "$REPO:$ALIAS";
        docker push "$REPO:$ALIAS";
      fi;
      docker push "$REPO:$TAG";