# Put this file next to your docker-compose.yml and
# run e.g. docker-compose up for local development
version: '3'
services:
  app:
    build:
      context: "."
      args:
      - "AKENEO_VERSION=${AKENEO_VERSION}"
      - "AKENEO_DIRECTORY=${AKENEO_DIRECTORY}"
      - "PACKAGES_DIRECTORY=${PACKAGES_DIRECTORY}"
    volumes:
      - "bin:/opt/akeneo-bootstrap/bin"
  web:
    environment:
      AWAIT_AKENEO_BUILD_DONE: 1
    volumes:
      - "./html:${AKENEO_DIRECTORY}"
      - "./packages:${PACKAGES_DIRECTORY}"
  setup:
    image: netresearch/akeneo-php:5
    volumes:
      - "./html:${AKENEO_DIRECTORY}"
      - "./packages:${PACKAGES_DIRECTORY}"
      - "bin:/opt/akeneo-bootstrap/bin"
    command: [ "/opt/akeneo-bootstrap/bin/akeneo-project", "create", "-f", "-i", "${AKENEO_DIRECTORY}", "-p", "${PACKAGES_DIRECTORY}" ]

volumes:
  bin: